#### Inicio de sesión de usuario
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email" : "test@example.com",
  "password" : "password123"
}

### Guardar manualmente el token (Reemplaza despues del login)
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ViMGU2YmZkZDhmZmFlOWFjNzBhYjYiLCJyb2xlIjoidXN1YXJpbyIsImlhdCI6MTc0NjQwNDgzMSwiZXhwIjoxNzU2NzcyODMxfQ.cnPwaO0gFgmywjNtRlvvRCi0DmvhK3-wNwqWIPqLUzQ

### Obtener algun client ID
GET http://localhost:5000/api/clients
Authorization: Bearer {{auth_token}}
Content-Type: application/json


### Guardar manualmente el ID del cliente
@clientId = 6817fc381d7d0dea0a8bc4e3

### Obtener un proyecto del Client por ID 
GET http://localhost:5000/api/clients/{{clientId}}/projects
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Guardar manualmente el ID del proyecto
@projectId = 681823c55e2a03017cd240cb

### Crear un nuevo Albarán
POST http://localhost:5000/api/albaranes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "projectId": "{{projectId}}",
  "clientId": "{{clientId}}",
  "description": "Descripción del albarán",
  "format": "materials",
  "materials": ["Material 1", "Material 2"],
  "workdate": "2023-10-01"
}

### Obtener todos los albaranes del USUARIO
GET http://localhost:5000/api/albaranes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Guardar manualmente el ID del albarán
@albaranId = 6818946e00930a9d31c7f6d6

### Obtener un albarán por ID
GET http://localhost:5000/api/albaranes/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### GENERAR un PDF del albarán por ID
PATCH  http://localhost:5000/api/albaranes/pdf/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Firmar un Albaran por ID 
PATCH http://localhost:5000/api/albaranes/sign/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "image": "file.png"
}
### DESCARGAR un PDF del albarán por ID
GET  http://localhost:5000/api/albaranes/pdf/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json