POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "ivassaaan@gmail.com",
  "password": "123456123",
  "role": "admin",
  "status": 1
}

###

GET http://localhost:3000/api/users 
 The first request creates a new user with the email
