### Borrar a todos los usuarios  SOLO PRUEBAS
DELETE http://localhost:5000/api/users
Content-Type: application/json

### Borrar a todos los clientes  SOLO PRUEBAS
DELETE http://localhost:5000/api/clients
Content-Type: application/json

### Borrar a todos los proyectos  SOLO PRUEBAS
DELETE http://localhost:5000/api/projects
Content-Type: application/json

### Borrar a todos los albaranes  SOLO PRUEBAS
DELETE http://localhost:5000/api/albaranes
Content-Type: application/json
