#### Inicio de sesión de usuario
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email" : "ivanmanuel121310@gmail.com",
  "password" : "password123"
}

### Guardar manualmente el token (Reemplaza despues del login)
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODJiOTk3MWY4MjFmNzBkMzAwNzMzN2QiLCJyb2xlIjoidXN1YXJpbyIsImlhdCI6MTc0NzY5NTY2NSwiZXhwIjoxNzU4MDYzNjY1fQ.MVCGM38hW1Z7ISXGHNpMuqS9UqYKsWf-f_QZKRtIih0

### Obtener algun client ID
GET http://localhost:5000/api/clients
Authorization: Bearer {{auth_token}}
Content-Type: application/json


### Guardar manualmente el ID del cliente
@clientId = 682baa29feba008c750cc268

### Obtener un proyecto del Client por ID 
### este endpoint devuelve todos los proyectos del cliente
GET http://localhost:5000/api/clients/{{clientId}}/projects
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Guardar manualmente el ID del proyecto
@projectId = 682bb88314fd0af4fec1f5f9

### Crear un nuevo Albarán
POST http://localhost:5000/api/albaranes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "projectId": "{{projectId}}",
  "clientId": "{{clientId}}",
  "description": "Descripción del albarán",
  "format": "materials",
  "materials": ["Material 1", "Material 2"],
  "workdate": "2023-10-01",
  "albaranCode": "ALB-001"
}

### Obtener todos los albaranes del USUARIO
GET http://localhost:5000/api/albaranes
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Guardar manualmente el ID del albarán
@albaranId = 681917fd49a65956afdfd0b5

### Obtener un albarán por ID
GET http://localhost:5000/api/albaranes/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### GENERAR un PDF del albarán por ID
PATCH  http://localhost:5000/api/albaranes/pdf/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Firmar un Albaran por ID 
PATCH http://localhost:5000/api/albaranes/sign/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "image": "file.png"
}
### DESCARGAR un PDF del albarán por ID
GET  http://localhost:5000/api/albaranes/pdf/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Eliminar un albarán por ID
DELETE http://localhost:5000/api/albaranes/{{albaranId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

