### Registro de usuario
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "ivanmanuel121310@gmail.com",
  "password": "password123"
}
### Inicio de sesión de usuario
POST http://localhost:5000/api/auth/login
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email" : "ivanmanuel121310@gmail.com",
  "password" : "password123"
}

### Guardar manualmente el token (Reemplaza después de la primera ejecución)
@auth_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODIzMTk2ZDRlNDk4NTk0ZDE1YzE3MWQiLCJyb2xlIjoidXN1YXJpbyIsImlhdCI6MTc0NzEzMDk3OCwiZXhwIjoxNzU3NDk4OTc4fQ.JMnbU6Q1ZkNeyA2uEj9Jte0vJ8XZmoOHE9xk5jszqAA

### Validación usando el token almacenado
POST http://localhost:5000/api/auth/validation
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "code": 372855
}
###
@UserId = 6823196d4e498594d15c171d

### Rellenar usuario loggeado
PATCH http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Test User",
  "about": "This is a test user",
  "phone": "+1234567890",
  "nif": "12345678A",
  "role" : "admin",
  "address": {
    "street": "Main St",
    "number": 123,
    "postal": 12345,
    "city": "Test City",
    "province": "Test Province"
  }
}

### Añadir una empresa al usuario
PATCH http://localhost:5000/api/users/company
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Test Company",
  "address": {
    "street": "Main St",
    "number": 123,
    "postal": 12345,
    "city": "Test City",
    "province": "Test Province"
  }
}

### Obtener la empresa vinculado al usuario 
GET http://localhost:5000/api/users/company
Authorization: Bearer {{auth_token}}
Content-Type: application/json


### Obtener información de todos los usuarios
GET http://localhost:5000/api/users
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Crear un nuevo usuario
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "password": "password123"
}



### Obtener un usuario por ID (utilizando el id del usuario creado)
GET http://localhost:5000/api/users/{{UserId}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Borrar a todos los usuarios 
DELETE http://localhost:5000/api/users
Authorization: Bearer {{auth_token}}
Content-Type: application/json

### Borrar un usuario por ID (utilizando el id del usuario creado)
DELETE http://localhost:5000/api/users/{{UserId}}
Authorization: Bearer {{auth_token}} 

### Usuarios: Subir foto (PATCH /api/users/image)

PATCH http://localhost:5000/api/users/image
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data

{
  "image": "image.png"
}


### Archivar usuario loggeado
PATCH http://localhost:5000/api/users/archive
Authorization: Bearer {{auth_token}}
Content-Type: application/json


### Desarchivar usuario loggeado
PATCH http://localhost:5000/api/users/restore
Authorization: Bearer {{auth_token}}
Content-Type: application/json


### recuperar contraseña 
### devuelve un token de recuperacion
POST http://localhost:5000/api/auth/recovery
Content-Type: application/json

{
  "email": "ivanmanuel1213@gmail.com"
}


###validar codigo de recuperacion
POST http://localhost:5000/api/auth/validation
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "code": 8862682
}
